### ISSUE TITLE
can not use namespace 'OrderedMap' as a type.

### ISSUE THREAD

**Issue by tarangpandya** [marijnh/orderedmap#9]
It seems like this latest commit has broke [prosemirror](https://github.com/ProseMirror/prosemirror/issues/1243) and 

subsequently telerik kendo editor and our build. 

The error:

![image](https://user-images.githubusercontent.com/23608276/154783577-48f69288-f26c-41cb-901d-635da5ddb7bd.png)

**Comment by marijnh** [comment]
Attached patch unpublishes the types again until we work this out. I'm not knowledgeable enough on the way legacy export/require stuff works in TS to figure out what's causing this error, but it's started occurring because prosemirror builds now use the types in this package rather than the ones on definitelytyped, and these somehow work differently.

@whawker

**Comment by whawker** [comment]
@marijnh Yikes ok, suspect it's the `export default OrderedMap` too.

Would you be open to publishing a OrderedMap beta/pre release so we test without risk of breaking people's builds?

**Comment by whawker** [comment]
Added a commit to #8 which I believe should fix this issue.

**Comment by marijnh** [comment]
Published 1.1.4, which restores the types in a way that seems to avoid this problem.
